### ISSUE TITLE
Improve metadata display

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-wizard-frontend#12]
There are some strange issues I'm seeing in the `Metrics Overview`. 

- [ ] `display_expression` is to thin
- [ ] Every input has a different style
- [ ] The fonts are a mess and partly not readable
- [ ] The `type` label doesn't fit in the selector input

![image](https://user-images.githubusercontent.com/130405/109676337-e7316c80-7b78-11eb-8af8-3e9705909401.png)

**Comment by kinnarr** [comment]
Also the edit "feature" doesn't exists in the backend
