### ISSUE TITLE
Strange message when setting a throttle node to empty

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-wizard-frontend#17]
![image](https://user-images.githubusercontent.com/130405/109801680-1a2e3b80-7c1f-11eb-913a-420de5aab333.png)

**Comment by kinnarr** [comment]
Is there anything else strange about this message, other than the node in the image having an empty input?

**Comment by bmario** [comment]
To clarify, I'm editing the throttle node itself in this screenshot.

I changed the type from throttle to empty, then the message appeared, and I have no idea what it wants to tell me.

**Comment by kinnarr** [comment]
It warns you that when you save this change, the inputs aka subnodes of the node will be delete.

But yes, the message should be improved:
- [ ] don't show with empty inputs
- [ ] show how the input count is reduced, e.g. `1 -> 0`, `5 -> 2`

**Comment by bmario** [comment]
Ideally, you shouldn't be able to set a node back to `Empty`. Instead, add a delete button for every node.

And as a corollary, it shouldn't be shown as `empty`, but `<red>Missing</red>`

**Comment by kinnarr** [comment]
This message is also shown when a sum node is set to a throttle node or a binary node is set to a throttle node, etc.
