### ISSUE TITLE
Throttle node needs a unit for the cooldown period

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-wizard-frontend#19]
![image](https://user-images.githubusercontent.com/130405/109802019-8d37b200-7c1f-11eb-8126-a51948db6386.png)

Note: I don't know the unit, but guessed it to be seconds

**Comment by kinnarr** [comment]
From the combinator documentation:

> ``<duration>`` is of the form ``<value><unit>``, e.g. ``2s`` or ``500 milliseconds``
